require("mason").setup()
--require("mason-lspconfig").setup({
--	ensure_installed = { "lua_ls", "pylsp", "rust_analyzer" }
--})
--
--local capabilities = require('cmp_nvim_lsp').default_capabilities()
--
--local lspconfig = require("lspconfig")
--
--lspconfig.pylsp.setup { capabilities = capabilities }
--lspconfig.rust_analyzer.setup { capabilities = capabilities }
--lspconfig.lua_ls.setup {
--	capabilities = capabilities,
--	settings = {
--		Lua = {
--			diagnostics = {
--				globals = {'vim'}
--			}
--		}
--	}
--}
--
